name:                 pokemon-analyzer
version:              0.1.0.0
visibility:           public
id:                   pokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp
key:                  pokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp
license:              MIT
abi:                  ab3ee0eb05859a6d9135755b66cc6203
exposed:              True
exposed-modules:      Api Logic Types
import-dirs:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/lib/x86_64-linux-ghc-9.6.6/pokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp

library-dirs:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/lib/x86_64-linux-ghc-9.6.6/pokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp

library-dirs-static:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/lib/x86_64-linux-ghc-9.6.6/pokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp

dynamic-library-dirs:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/lib/x86_64-linux-ghc-9.6.6

data-dir:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/share/x86_64-linux-ghc-9.6.6/pokemon-analyzer-0.1.0.0

hs-libraries:         HSpokemon-analyzer-0.1.0.0-8oaBGJpwiNaF1zLNEdDNHp
depends:
    aeson-2.1.2.1-1g7K6uZ9GHJKLobSRH2PQh base-4.18.2.1
    bytestring-0.11.5.3 containers-0.6.7
    http-conduit-2.3.8.3-3mAPscD4vQZ5aQjgTYPig1
    http-types-0.12.4-2RWyQgC77LV4cEzuFRCNtl text-2.0.2
    transformers-0.6.1.0 vector-0.13.1.0-Aqc2YUE1Egs5WmXVMbcJ5T

haddock-interfaces:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/doc/pokemon-analyzer-0.1.0.0/pokemon-analyzer.haddock

haddock-html:
    /workspaces/perso-2026a-ODiogorocha/pokemon_analyzer/.stack-work/install/x86_64-linux-tinfo6-libc6-pre232/e481cb8b32c8d406e64f360f892315fe7d9ced0ccd616da93d5719e20643dc12/9.6.6/doc/pokemon-analyzer-0.1.0.0
